
/**
 * @file defines.h
 *
 * @brief Configuration macros for the radar system.
 *
 * This file contains the sensor front-end parameters.
 * For reference regarding the parameters, please refer to https://software-dl.ti.com/ra-processors/esd/MMWAVE-L-SDK/05_05_00_02/exports/api_guide_xwrL64xx/MOTION_AND_PRESENCE_DETECTION_DEMO.html
 *   section "Configuration (.cfg) File Format (CLI INTERFACE)"
 *
 * The configuration settings can be generated with the "mmWave Sensing Estimator" tool (https://dev.ti.com/gallery/view/mmwave/mmWaveSensingEstimator/ver/2.4.0/)
 *
 * This file was auto-generated by the script 'chirp_config_to_defines.py' from the config file 'PresenceDetect.cfg' on 2025-04-18 14:34:00
 */

/* frameCfg */
#define CLI_NUM_CHIRPS_PER_BURST     8
#define CLI_NUM_CHIRPS_ACCUM         0
#define CLI_BURST_PERIOD             403
#define CLI_W_BURST_PERIOD           (10.0 * CLI_BURST_PERIOD)   // calculated value, not contained in config
#define CLI_NUM_BURSTS_PER_FRAME     1
#define CLI_FRAME_PERIOD             (((float)(250) * 40000000.0) / 1000.0)   // for reference: value 250 is from config
#define CLI_NUM_FRAMES               0

/* chirpTimingCfg */
#define CLI_CHIRP_IDLE_TIME          (10.0 * 6)        // for reference: value 6 is from config
#define CLI_CHIRP_ADC_START_TIME     (28 << 10)        // for reference: value 28 is from config
#define CLI_CHIRP_TX_START_TIME      (50.0 * 0)        // for reference: value 0 is from config
#define CLI_CHIRP_SLOPE              90
#define CLI_START_FREQ               59.75
#define CLI_CHIRP_FREQ_SLOPE         ((CLI_CHIRP_SLOPE * 1048576.0) / (3 * 100 * 100))         // calculated value, not contained in config
#define CLI_CHIRP_START_FREQ         ((CLI_START_FREQ * 1000.0 * 256.0) / (300))               // calculated value, not contained in config

/* channelCfg */
#define CLI_CHA_CFG_RX_BITMASK       7
#define CLI_CHA_CFG_TX_BITMASK       3
#define CLI_CHA_CFG_MISC_CTRL        0

/* chirpComnCfg */
#define CLI_NUM_ADC_SAMPLES          128
#define CLI_NUM_RBINS                (mathUtils_pow2roundup(CLI_NUM_ADC_SAMPLES) / 2)    // calculated value, not contained in config
#define CLI_DIG_OUT_SAMPLING_RATE    20
#define CLI_ADC_SAMPLING_RATE        (100.0 / CLI_DIG_OUT_SAMPLING_RATE)                 // calculated value, not contained in config
#define CLI_DIG_OUT_BITS_SEL         0
#define CLI_DFE_FIR_SEL              0
#define CLI_MIMO_SEL                 4
#define CLI_CHIRP_RAMP_END_TIME      (10.0 * 30)       // for reference: value 30 is from config
#define CLI_CHIRP_RX_HPF_SEL         0

/* Factory Calibration */
#define CLI_FACCALCFG_RX_GAIN        40
#define CLI_FACCALCFG_TX_BACKOFF_SEL 0 * 2             // for reference: value 0 is from config
#define CLI_FACCALCFG_FLASH_OFFSET   0x1ff000

/* sensorStart */
#define CLI_SENSOR_START_FRM_TRIG    0
#define CLI_SENSOR_START_LB_EN       0
#define CLI_SENSOR_START_MON_EN      0
#define CLI_SENSOR_START_TRIG_TIMER  0

#define CLI_C_MISC_SETTINGS          0
#define CLI_HPF_FAST_INIT_DURATION   15U
