#define NUM_TX_ANTENNAS 2
#define NUM_RX_ANTENNAS 3
#define NUM_VIRT_ANTENNAS (NUM_TX_ANTENNAS*NUM_RX_ANTENNAS)
#define NUM_ADC_SAMPLES 128 // hardcoded in https://dev.ti.com/gallery/view/mmwave/mmWaveSensingEstimator/ver/2.4.0/ and also used in MOTION_AND_PRESENCE_DETECTION_DEMO
#define NUM_BURSTS_PER_FRAME 1 // from MOTION_AND_PRESENCE_DETECTION_DEMO
#define NUM_CHIRPS_PER_BURST 8 // from MOTION_AND_PRESENCE_DETECTION_DEMO
#define NUM_CHIRPS_PER_FRAME (NUM_BURSTS_PER_FRAME*NUM_CHIRPS_PER_BURST)
